name = "Minecraft Horizons 2"
author = "Losy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "697671a845c6a7eaa71e37fd4f3dd913061625b4a62e36780a36a2763689285f"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
