name = "Minecraft Horizons 2"
author = "Losy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90659fda66d8555a4178cb2b730c2c505c46c03ad02b0e67cd580b6d3d68d906"

[versions]
forge = "47.4.22"
minecraft = "1.20.1"
