name = "Minecraft Como Chingan"
author = "Jesús de la Casa"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a1e24424b75e47ecea3de100b385424cf4afdf360dc91e9a97cf3ed25f161f4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
