name = "Minecraft Como Chingan"
author = "Jesús de la Casa"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d416cf1b109bfbfb9b8cc29473244e5463e270935498e794ca8dda3dc845827"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
