name = "Minecraft Como Chingan"
author = "Jesús de la Casa"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "792488a625799728578994d10f7a1eaa6b2b13fcc777d9cf34de3bc92b0a5a62"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
