name = "Minecraft Aeronautics by PG"
author = "Jesús de la Casa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "960cf61b3cd7d4941605a0273ae79a3feb87f51140c06c575b6c110b56081f6b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
