name = "Minecraft Aeronautics by PG"
author = "Jesús de la Casa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2efeace7ed8294cf25e77508b67b0179bab22f24a1490912b6490fc6cbd87f7f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
