name = "Minecraft Aeronautics by PG"
author = "Jesús de la Casa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "582671ae9ceb4118a7ad7d547450d7ff9f6500118de3752dac93423e2c445cf6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
