name = "Minecraft Horizons"
author = "Jesús de la Casa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ea958a6a33cd8e4da912b7e1f3fe26358605fcbacccbd89f5afa30ce9d398f6"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
