name = "Minecraft Horizons"
author = "Jesús de la Casa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04860538fae4d9b0ebe3f316e485f657cc0572226c20e336d1ce9a832ea340c1"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
