name = "Minecraft Horizons"
author = "Jesús de la Casa"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "343cadf3f07a61c8eae99cf9097609c99a190f9736ec56e8db755b5a1043a875"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
